-- Founder access: the first 50 accounts get every premium feature, free, for
-- good. Run this once in the Supabase SQL editor.
--
-- The position is a column in this table rather than a counter somewhere,
-- because a counter can be double-counted, reset by a redeploy, or drift from
-- reality. Here the number is assigned once, stored, and never recomputed.

create table if not exists public.founders (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  n          bigint generated by default as identity,
  claimed_at timestamptz not null default now(),
  constraint founders_n_unique unique (n)
);

-- Seed every account that already exists, numbered by when it actually signed
-- up. Without this the numbers would be handed out in "whoever opens the app
-- next" order, so someone who joined early but has not launched the app in a
-- while could be pushed past 50 by a brand new signup. Their slot is theirs
-- from this moment, whether or not they ever open the app again.
--
-- row_number() is used instead of letting the identity column assign the
-- values, because only an explicit ORDER BY guarantees the numbering follows
-- signup order.
insert into public.founders (user_id, n)
select id, row_number() over (order by created_at asc)
from auth.users
on conflict (user_id) do nothing;

-- The seed above set n by hand, which leaves the identity sequence still
-- sitting at 1. Without this, the next account to claim would be handed a
-- number that is already taken and the insert would fail.
select setval(
  pg_get_serial_sequence('public.founders', 'n'),
  coalesce((select max(n) from public.founders), 0) + 1,
  false
);

-- Nothing reads this table from the browser. The Worker uses the service role,
-- which bypasses RLS entirely, so enabling RLS with no policy is what we want:
-- it denies every anon and authenticated client while leaving the Worker
-- working. Without this line the table would be readable by anyone with the
-- public anon key.
alter table public.founders enable row level security;

-- What you should see: one row per existing account, numbered from 1.
select
  count(*)                            as accounts_seeded,
  count(*) filter (where n <= 50)     as have_free_access,
  greatest(0, 50 - count(*))          as slots_left
from public.founders;
